name: CD - Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag: 
        description: "Github action output"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
          -var="aws_region=${{ secrets.AWS_REGION }}" \
          -var="ami_id=ami-xxxxxxxx" \
          -var="key_name=your-key-name" \
          -var="docker_image=${{ secrets.DOCKER_USERNAME }}/strapi:${{ github.event.inputs.image_tag }}"
        working-directory: terraform
