name: CD - Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag from CI"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false -var="docker_image=${{ secrets.DOCKER_USERNAME }}/strapi:${{ github.event.inputs.image_tag }}"


      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var="docker_image=${{ secrets.DOCKER_USERNAME }}/strapi:${{ github.event.inputs.image_tag }}"

